# Numpy Assignment

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of integers from 10 to 50

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with value ranging from 0 to 8

In [10]:
data=[0,1,2,3,4,5,6,7,8]

In [11]:
data 

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
type(data)

list

In [13]:
arr=np.array(data)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
arr2d=arr.reshape(3,3)

In [17]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate random number between 0 to 1

In [19]:
np.random.rand()

0.2680050135164349

#### Use NumPy to generate an array of 25 random numbers sampled from a Standard Normal Distribution

In [20]:
np.random.randn(25)

array([ 1.36070455, -0.35909983,  0.03587735,  0.37175786,  0.56257577,
       -2.29190754,  1.70674839,  0.64691546,  2.09394712,  0.15533341,
       -1.08246788, -0.57660657, -0.22974754,  0.7332042 ,  1.0885552 ,
        0.17737457, -0.73864214, -0.49624806,  0.97769624,  0.08154297,
       -1.79503576,  0.40764277,  0.19327708, -0.79375315,  1.77038708])

#### Create a following matrix:

In [21]:
array=np.arange(0.01, 1.01, 0.01).reshape(10, 10)

In [22]:
array

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

 #### Create an array of linearly spaced points between 0 and 1

In [23]:
arr2=np.linspace(0, 1, 20)

In [24]:
arr2

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [25]:
arr=np.arange(1,26).reshape(5,5)

In [26]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr[3,4]

20

In [31]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr[4:5]

array([[21, 22, 23, 24, 25]])

In [36]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
matrix=np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
std_dev=np.std(matrix)
print(std_dev)

7.211102550927978


In [43]:
arr.sum(axis=1)[0]

15

In [39]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
arr[0:5,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [41]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])